# Generated by Django 4.1.4 on 2023-04-06 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategori İsmi')),
            ],
        ),
        migrations.CreateModel(
            name='userProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='isim')),
                ('surname', models.CharField(max_length=50, verbose_name='soyisim')),
                ('username', models.CharField(max_length=50, verbose_name='kullanıcı adı')),
                ('katilim', models.DateTimeField(verbose_name='katılma tarihi')),
                ('profil_image', models.FileField(upload_to=None, verbose_name='profil foto')),
                ('phone', models.IntegerField(verbose_name='telefon numarası')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_ismi', models.CharField(max_length=50, verbose_name='Ev Adı')),
                ('ülke', models.CharField(max_length=50, verbose_name='Ülke')),
                ('lokasyon', models.TextField(verbose_name='Konum Bilgisi')),
                ('yayin_tarihi', models.DateTimeField(verbose_name='Yayın Tarihi')),
                ('foto_1', models.FileField(upload_to=None, verbose_name='Ev Foto1')),
                ('foto_2', models.FileField(upload_to=None, verbose_name='Ev Foto2')),
                ('foto_3', models.FileField(upload_to=None, verbose_name='Ev Foto3')),
                ('günlük_ücret', models.FloatField(verbose_name='Günlük Ücret')),
                ('ev_sahibi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ev Sahibi')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.category', verbose_name='Kategori')),
            ],
        ),
    ]
