# Generated by Django 4.1.4 on 2023-04-08 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cimage',
            field=models.FileField(null=True, upload_to=None, verbose_name='kategori ico'),
        ),
        migrations.AlterField(
            model_name='house',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.category', verbose_name='Kategori'),
        ),
    ]
